version: '3.8'

services:
  mysql:
    image: mysql:8.0 # หรือใช้ mysql:5.7 ถ้ามีปัญหากับเวอร์ชัน 8.0
    platform: linux/amd64 # เพิ่มบรรทัดนี้เพื่อแก้ปัญหา ARM
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: the_24_game
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64 # เพิ่มบรรทัดนี้เพื่อแก้ปัญหา ARM
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"

volumes:
  mysql-data:
